name: TFSec

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  schedule:
    - cron: "0 21 * * SUN"

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  scan:
    name: Scan
    uses: cupel-co/workflows/.github/workflows/tfsec.yml@v0.2.0
